### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jaumeortola** [Softcatala/separador-sillabes#1]
- [x] Fer que serveixi també per a comptar la mètrica de versos. Caldria tenir en compte sinalefes o elisions fonètiques. L'entrada hauria de ser una àrea de text, i fer recompte de síl·labes per cada línia. 
- [x] Afegir una explicació senzilla de com funciona la separació de paraules a final de ratlla, amb les convencions usuals (amb enllaços).  
- [x] Enllaços a diccionaris descarregables de partició de paraules i instruccions.
